---
language: node_js
node_js:
- "stable"
env:
  global:
    - COVERAGE=false
matrix:
  include:
    - node_js: "stable"
      env: COVERAGE=true
before_install:
  - npm install codecov.io
after_script:
 - "[ $COVERAGE == false ] || npm run coverage"
 - "[ $COVERAGE == false ] || cat ./coverage/lcov.info | ./node_modules/.bin/codecov"
