---
language: node_js
node_js:
- "stable"
env:
  global:
    - COVERAGE=false
matrix:
  include:
    - node_js: "stable"
      env: COVERAGE=true
before_install:
  - "[ $COVERAGE == false ] || npm install coveralls"
after_script:
  - "[ $COVERAGE == false ] || ./node_modules/.bin/isparta cover ./node_modules/.bin/mocha --report lcovonly -- -R spec"
  - "[ $COVERAGE == false ] || cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
